name: Update Playlist
on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর অটোমেটিক চলবে
  workflow_dispatch: # তুমি চাইলে নিজেও ক্লিক করে রান করতে পারবে

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run scraper
        run: python scraper.py
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Auto-update playlist" || exit 0
          git push
          
